### ISSUE TITLE
Serial2-6 for recieve on Teensy 3.6

### ISSUE THREAD

**Issue by ScholliYT** [ssilverman/TeensyDMX#1]
Seems like Serial3 and Serial4 (so far as I tested) are not working for recieve on my Teensy 3.6. If I connected a DMX Singal to Serial1 (Pin0) or Serial2 (pin9) everything works fine. Connecting it to Serial3 or Serial4, I cant recieve any values. I'm using the Flasher.ino provided in your examples. 

Would be nice if you can fix that :) 
Or is this just a problem on my side?

**Comment by ssilverman** [comment]
I haven't yet added support for those serial ports.

**Comment by ssilverman** [comment]
I made a new branch, "AddSerials4to6". Try that out and see if it works for you. If it does, I'll commit it to the master branch.

**Comment by ScholliYT** [comment]
Ok I'll give it a try

**Comment by ssilverman** [comment]
I just made a new version and tag, v2.2.0. I'll just mark this as closed and if there's any problems with the new code, I'll make a new issue.
