### ISSUE TITLE
Example pinout?

### ISSUE THREAD

**Issue by soulgriever** [ssilverman/TeensyDMX#4]
Novice here, is their any examples for using this library with a 3pin XLR DMX light?

Also is an RS485 needed or could a Teensy LC be used standalone with the light

**Comment by ssilverman** [comment]
DMX is differential pair, you’d need an RS-485 adapter that goes between the DMX and the Teensy. See https://en.wikipedia.org/wiki/DMX512 for pin guidance.

**Comment by ssilverman** [comment]
I just added a _Hardware connection_ section to the README that gives an overview of how to connect a Teensy to an RS-485 transceiver.
