### ISSUE TITLE
Teensy Locks Up after several Connects / Disconnects of DMX from certain sources. 

### ISSUE THREAD

**Issue by pyronox** [ssilverman/TeensyDMX#6]
It seems to be possible to to cause the Teensy (Teensy 3.2 (96Mhz (Overclocked))  to lock up when receiving DMX from certain lighting desks and physically connecting / disconnecting the dmx cable. 

The timings of the Offending DMX source are as follows:
Refresh: 20Hz
Break Length: 238 to 280uS (**)
MAB: 23uS
Channels Rx:  512

When the lock up occurs, only a power cycle fixes it .

**Comment by ssilverman** [comment]
Thanks for reporting this issue. Some questions:
1. Is it possible to narrow down more timing ranges that cause the lock-up?
2. Does this only happen for you when running the Teensy overclocked?

**Comment by pyronox** [comment]
Hey,

I haven't got round to setting up some more tests with this, but will try to in the next week or so.

Thanks.

**Comment by ssilverman** [comment]
Does release v3.1.1 work for you? I wonder if it’s the same problem as here: https://forum.pjrc.com/threads/58407-Can-t-get-Teensy-LC-to-receive-DMX

If so, then I clearly introduced a problem in v3.2.0.

**Comment by ssilverman** [comment]
I've released v4.0.0-alpha. See if this fixes the problem for you.

**Comment by ssilverman** [comment]
I fixed another issue that was affecting Teensy LC in v4.0.0-alpha.1

**Comment by pyronox** [comment]
Hi, apologies for the delay in responding.... I accidentally blew up my original test board. 

Building another at the moment 👍 

Then will go through your previous questions, and test with the new release.

**Comment by ssilverman** [comment]
@pyronox Any word on this?

**Comment by ssilverman** [comment]
I duplicated this setup as closely as I could and could not get the lockup to happen. I'm going to mark this as closed. If there's further issues, go ahead and re-open or make another issue.
